name: Release Beta

on:
  push:
    branches: [ beta ]

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 8

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Install the dependencies
      run: pnpm install

    - name: Configure npm for authentication
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
        echo "@payloadcms:registry=https://your-custom-registry-url/" >> ~/.npmrc

    - name: Initialize Git user
      run: |
        git config --global user.email "shubpramanik241@gmail.com"
        git config --global user.name "sourabpramanik"

    - name: Log git status
      run: git status

    - name: Run release
      run: pnpm release:beta
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

